-- Run only in the new Thanos Supabase project.
-- This replaces the previous Thanos application schema.
-- It drops only the Thanos application objects listed below.

begin;

drop view if exists public.qualifying_leads cascade;
drop table if exists public.enrichment_jobs cascade;
drop table if exists public.companies cascade;
drop table if exists public.raw_events cascade;
drop table if exists public.stream_checkpoints cascade;
drop table if exists public.worker_status cascade;

create table public.raw_events (
    id bigint generated by default as identity primary key,
    event_type text,
    company_number text,
    payload jsonb not null,
    received_at timestamptz not null default now()
);

create table public.companies (
    company_number text primary key,
    company_name text not null,
    date_of_creation date not null,
    sic_codes jsonb not null default '[]'::jsonb,
    raw_data jsonb not null default '{}'::jsonb,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    enrichment_status text not null default 'not_required',
    is_lead boolean not null default false,
    lead_status text not null default 'qualified',
    matched_buzzwords jsonb not null default '[]'::jsonb,
    matched_sic_codes jsonb not null default '[]'::jsonb,
    incorporated_today boolean not null default true,
    last_screened_at timestamptz,
    enriched_at timestamptz
);

create table public.enrichment_jobs (
    id bigint generated by default as identity primary key,
    company_number text not null references public.companies(company_number) on delete cascade,
    enrichment_scope text not null default 'initial_rest',
    status text not null default 'pending',
    attempts integer not null default 0,
    last_error text,
    created_at timestamptz not null default now(),
    started_at timestamptz,
    completed_at timestamptz,
    unique(company_number, enrichment_scope)
);

create table public.stream_checkpoints (
    stream_name text primary key,
    timepoint bigint,
    connection_status text not null default 'disconnected',
    last_event_at timestamptz,
    last_heartbeat_at timestamptz,
    updated_at timestamptz not null default now()
);

create table public.worker_status (
    worker_name text primary key,
    process_id text,
    status text not null default 'starting',
    heartbeat_at timestamptz,
    last_event_at timestamptz,
    events_received bigint not null default 0,
    events_committed bigint not null default 0,
    last_error text,
    updated_at timestamptz not null default now()
);

create index companies_lead_idx
    on public.companies(is_lead, date_of_creation, first_seen_at desc);

create index companies_date_idx
    on public.companies(date_of_creation);

create view public.qualifying_leads as
select
    company_number,
    company_name,
    date_of_creation,
    sic_codes,
    enrichment_status,
    lead_status,
    matched_buzzwords,
    matched_sic_codes,
    incorporated_today,
    raw_data,
    first_seen_at,
    last_seen_at
from public.companies
where is_lead = true
  and incorporated_today = true;

commit;

select table_schema, table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
      'raw_events',
      'companies',
      'enrichment_jobs',
      'stream_checkpoints',
      'worker_status'
  )
order by table_name;

select table_schema, table_name
from information_schema.views
where table_schema = 'public'
  and table_name = 'qualifying_leads';
